Table user {
    id serial [pk]
    username varchar(255) [unique]
    email varchar(255) [unique, not null]
    password varchar(255) [not null]
    avatar_url varchar(255)
    refresh_token varchar(1024)
    created_at timestamp [default: `now()`]
    updated_at timestamp
}

Table user_stats {
    user_id integer [pk, ref: > user.id]
    total_clickcoins bigint [default: 0]
    total_clicks bigint [default: 0]
}

Table user_characteristics {
    user_id integer [pk, ref: > user.id]
    coins_per_click integer [default: 1]
    passive_coins_income integer [default: 0]
}

enum offer_status {
  active
  completed
  cancelled
}

Table user_offer {
    id serial [pk]
    user_id integer [ref: > user.id]
    coin_count integer [not null]
    price_per_coin integer [not null]
    status offer_status [default: offer_status.active]
    created_at timestamp [default: `now()`]
}

Table achievement_user {
    user_id integer [pk, ref: > user.id]
    achievement_id integer [pk, ref: > achievement.id]
    obtained_at timestamp [not null, default: `now()`]

    indexes {
        (user_id, achievement_id) [pk]
    }
}

Table upgrade_user {
    user_id integer [pk, ref: > user.id]
    upgrade_id integer [pk, ref: > upgrade.id]
    obtained_at timestamp [not null, default: `now()`]
    
    indexes {
        (user_id, upgrade_id) [pk]
    }
}

Table achievement {
    id smallserial [pk]
    title varchar(32)
    description varchar(128)
}

Table upgrade {
    id smallserial [pk]
    title varchar(32)
    description varchar(128)
    price integer
}